spring.application.name=task-management-api
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRES_IN}
